### ISSUE TITLE
Not Working with Audio Station

### ISSUE THREAD

**Issue by PakNakal** [robertovg/audiostation-steroids#4]
I am using Synology DSM 6 Beta and have Audio Station installed, but I can't get the Last.fm authorization to work.  Has this extension stopped working with the most recent version of Audio Station?

**Comment by PakNakal** [comment]
Is this add in still being updated/developed? I would love to use it, but I can't get it connected with Last.fm.

**Comment by robertovg** [comment]
Thanks for this message, honestly I didn't spend much time on this plugin right now, till now. I just make a new package and deployed to Chrome Web Store. I migrated the servers and now with the new Versión: 1.0.2 everything should be ok.

Again thank you for your time, and sorry for the big delay. I hope it's still useful

**Comment by PakNakal** [comment]
Thanks!  Works great now!

Zack
